"""
Script for parsing through the per-instance config file and returning the relevant information for the instance.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict


CONFIG_PATH = Path("/root/config/dsr_instances.json")  # Path to the per-instance config file


@dataclass(frozen=True)
class InstanceConfig:
    """Class for storing the relevant information for the instance."""
    name: str
    display: str
    display_num: int
    desktop_name: str
    wineprefix: str | None
    vnc_port: int | None
    dsr_user_id: str | None
    dsr_save_root: str | None
    dsr_save_dir: str | None


def _load_config(path: Path = CONFIG_PATH) -> Dict[str, Any]:
    """Load the instance config file from the given path"""
    if not path.is_file():
        raise FileNotFoundError(f"Missing instance config: {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        raise RuntimeError(f"Failed to parse JSON config {path}: {e}") from e


def load_instances(path: Path = CONFIG_PATH) -> Dict[str, Any]:
    """Load the instance config file from the given path"""
    cfg = _load_config(path)
    instances = cfg.get("instances")
    if not isinstance(instances, dict):
        raise RuntimeError(f"Config {path} must contain an 'instances' object")
    return instances


def resolve_instance(instance_name: str, path: Path = CONFIG_PATH) -> InstanceConfig:
    """
    Resolve per-instance runtime settings needed to interact with a specific DSR instance.
    
    The config is generated by `scripts/generate_config.py` and used by
    `/root/scripts/run_instance.py`.
    """
    instances = load_instances(path)
    inst = instances.get(instance_name)
    if not isinstance(inst, dict):
        available = ", ".join(sorted(instances.keys()))
        raise KeyError(f"Unknown instance '{instance_name}'. Available: {available}")

    display_num = inst.get("display_num")
    if isinstance(display_num, int):
        display = f":{display_num}"
    else:
        # Support manual configs that include a direct DISPLAY string (e.g. ':99').
        display = inst.get("display")
        if not (isinstance(display, str) and display.strip()):
            raise RuntimeError(f"Instance '{instance_name}' missing integer 'display_num' (or string 'display') in {path}")
        display = display.strip()
        if display.startswith(":") and display[1:].isdigit():
            display_num = int(display[1:])
        else:
            display_num = -1

    desktop_name = inst.get("desktop_name")
    if not (isinstance(desktop_name, str) and desktop_name.strip()):
        # Mirror scripts/run_instance.py default.
        desktop_name = f"DSR_{instance_name}"

    wineprefix = inst.get("wineprefix")
    if isinstance(wineprefix, str) and wineprefix.strip():
        wineprefix = wineprefix.strip()
    else:
        wineprefix = os.environ.get("WINEPREFIX")

    vnc_port = inst.get("vnc_port")
    vnc_port = vnc_port if isinstance(vnc_port, int) else None

    dsr_user_id = inst.get("dsr_user_id")
    dsr_user_id = dsr_user_id.strip() if isinstance(dsr_user_id, str) and dsr_user_id.strip() else None

    dsr_save_root = inst.get("dsr_save_root")
    dsr_save_root = dsr_save_root.strip() if isinstance(dsr_save_root, str) and dsr_save_root.strip() else None

    dsr_save_dir = inst.get("dsr_save_dir")
    dsr_save_dir = dsr_save_dir.strip() if isinstance(dsr_save_dir, str) and dsr_save_dir.strip() else None

    return InstanceConfig(name=instance_name, display=display, display_num=display_num, desktop_name=str(desktop_name), wineprefix=wineprefix, vnc_port=vnc_port, dsr_user_id=dsr_user_id, dsr_save_root=dsr_save_root, dsr_save_dir=dsr_save_dir)
